import os
import re
import io
from dotenv import load_dotenv
from granite_service import GraniteService
from rag import RAGEngine

# Load env variables
load_dotenv()

class NAACChatbot:
    """
    Manages conversational workflows, applies strict NAAC-centric prompt rules,
    retains citations, and compiles beautiful PDF reports for download.
    """
    def __init__(self, granite_service: GraniteService, rag_engine: RAGEngine):
        self.granite = granite_service
        self.rag = rag_engine
        
    def ask(self, question: str, n_results: int = 5) -> dict:
        """
        Executes semantic search against ChromaDB, forms a strict prompt, 
        queries IBM Granite, and returns the response with source documents.
        """
        # 1. Retrieve Context from ChromaDB
        rag_results = self.rag.query(question, n_results=n_results)
        retrieved_context = rag_results["context"]
        sources = rag_results["sources"]

        # 2. Strict Prompt Template as requested
        prompt = f"""Answer only using the provided institutional and NAAC documents.

Context:
{retrieved_context}

Question:
{question}

If the answer is not available in the documents, respond:

"I could not find sufficient information in the uploaded NAAC and institutional documents."
"""

        # 3. Call Granite
        system_prompt = (
            "You are a helpful and meticulous Faculty Assistant for NAAC Accreditation. "
            "You strictly follow the rule to answer ONLY using the provided documents."
        )
        response_text = self.granite.generate(prompt=prompt, system_prompt=system_prompt)
        
        return {
            "answer": response_text,
            "sources": sources,
            "context_used": retrieved_context
        }

def export_response_to_pdf(title: str, text: str) -> bytes:
    """
    Compiles text/markdown into an elegant academic PDF utilizing ReportLab
    with styled headers, rules, margins, and download buffering.
    """
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    from reportlab.lib import colors
    
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=letter, 
        rightMargin=45, 
        leftMargin=45, 
        topMargin=45, 
        bottomMargin=45
    )
    story = []
    
    # Build a professional Slate-Blue visual style
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontSize=18,
        leading=22,
        textColor=colors.HexColor('#003366'), # Deep University Blue
        spaceAfter=12
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#555555'),
        spaceAfter=8
    )
    
    heading2_style = ParagraphStyle(
        'Heading2Style',
        parent=styles['Heading2'],
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#0066cc'), # Lighter blue
        spaceBefore=12,
        spaceAfter=6
    )
    
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#222222'),
        spaceAfter=8
    )
    
    bullet_style = ParagraphStyle(
        'BulletStyle',
        parent=styles['Normal'],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#222222'),
        leftIndent=15,
        spaceAfter=4
    )
    
    # 1. Add headers
    story.append(Paragraph(title.upper(), title_style))
    story.append(Paragraph("Generated by NAAC Assist AI — Accreditation Documentation Platform", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#003366'), spaceAfter=15))
    
    # 2. Parse lines and convert markdown format to ReportLab paragraph tags
    lines = text.split("\n")
    for line in lines:
        line_str = line.strip()
        if not line_str:
            story.append(Spacer(1, 6))
            continue
            
        # Headers conversion
        if line_str.startswith("###") or line_str.startswith("##") or line_str.startswith("#"):
            hdr_text = line_str.lstrip("#").strip()
            # Convert simple bold inside header
            hdr_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', hdr_text)
            story.append(Paragraph(hdr_text, heading2_style))
            
        # Bullet points conversion
        elif line_str.startswith("*") or line_str.startswith("-"):
            bullet_text = line_str[1:].strip()
            bullet_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', bullet_text)
            bullet_text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', bullet_text)
            story.append(Paragraph(f"&bull; {bullet_text}", bullet_style))
            
        # Numerical list bullet conversion
        elif re.match(r'^\d+\.', line_str):
            num_text = line_str.strip()
            num_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', num_text)
            num_text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', num_text)
            story.append(Paragraph(num_text, bullet_style))
            
        # Standard paragraph conversion
        else:
            para_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line_str)
            para_text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', para_text)
            # Support basic Markdown links conversion [Text](URL)
            para_text = re.sub(r'\[(.*?)\]\((.*?)\)', r'<font color="#0066cc"><u>\1</u></font>', para_text)
            story.append(Paragraph(para_text, body_style))
            
    # Build document
    try:
        doc.build(story)
        pdf_data = buffer.getvalue()
        buffer.close()
        return pdf_data
    except Exception as e:
        print(f"Error compiling PDF: {e}")
        # Return fallback plain-text encoded pdf
        return bytes(f"PDF compilation error: {e}\n\n{text}", "utf-8")
